server:
    port: 8080

spring:
    datasource:
        url: jdbc:mariadb://a372be0564d58424b9f503dd696e766a-1897922469.ap-northeast-2.elb.amazonaws.com:3306/CLOUD
        driver-class-name: org.mariadb.jdbc.Driver
        username: cloud
        password: Skala25a!23$
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

management:
    server:
        port: 8081 # Actuator 포트 설정
    endpoints:
        web:
            exposure:
                include: '*' # Prometheus endpoint 노출
    metrics:
        enable:
            all: true # 모든 기본 메트릭 활성화
    endpoint:
        prometheus:
            enabled: true # Prometheus endpoint 활성화
