apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sk036-stock-be
  namespace: skala-argocd
spec:
  destination:
    namespace: skala-practice
    server: https://96BD83E8CE5CE0396D006BC5CEB350B0.gr7.ap-northeast-2.eks.amazonaws.com
  project: class-2
  source:
    path: k8s
    repoURL: https://github.com/chaerish/stock-be
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=background
